### ISSUE TITLE
getpt failed when attempting to remaster Ubuntu 15.04

### ISSUE THREAD

**Issue by thomasstevenson** [kamilion/customizer#102]
I'm using the latest version of Customizer taken from GitHub (labeled as verison 4.1.1 in the app) on an Ubuntu 15.04 64 bit host system, attempting to remaster Ubuntu 15.04 64 bit.
As soon as I select the .iso file and Customizer extracts its data for customization, I get the following error when opening any Terminal window: 

```
There was an error creating the child process for this terminal
getpt failed: No such file or directory
```

![customizer-getpt](https://cloud.githubusercontent.com/assets/7741618/8111227/80dbcf34-1058-11e5-821c-251482455fc2.png)

This error prevents me from entering anything into the Terminal and also closes some apps on the host system (eg. Google Chrome). This error appears in every Terminal window I open, both in Customizer and when opening the Terminal from the Dash. The only way to recover from this error is to restart the host computer and not open Customizer.

P.S. I have made sure that the md5sum of the Ubuntu .iso file is correct.

**Comment by ghost** [comment]
@thomasstevenson 
From what I have tested personally, it worked on 14.04 64-bit host system against 14.04 64-bit ISO image. That was the last time I have tested using Customizer 4.1 release.

As for this issue, a quick googling on the error `getpt failed: No such file or directory` suggested that you may have modified your `/etc/fstab` file for whatever reason. Which might be nothing to do with Customizer itself.

From what you mentioned in the first sentence:

> [...] an Ubuntu 15.04 64 bit host system, attempting to remaster Ubuntu 15.04 64 bit.

So, is the host system running a freshly installed system? Additionally, was the host system installed using the official Ubuntu ISO image?

P.S. Ubuntu 15.04 itself is not without issue.

**Comment by thomasstevenson** [comment]
I'm running a clean install of Ubuntu 15.04 on my host system. The only changes that I made after the installation of Ubuntu 15.04 was the installation of Customizer and its dependencies.

I used the official Ubuntu 15.04 64 bit .iso file downloaded from ubuntu.com for both the installation of the host OS and for the remastering process in Customizer.

**Comment by ghost** [comment]
I have confirmed this issue, tested using latest Customizer from **master** branch, on 15.04 64-bit host system against 15.04 64-bit ISO image.

Apparently, when remastering against newer release of *buntu, only the chroot Terminal feature is affected. Other features such as Desktop works as usual.

This issue is likely related, since 15.04 is the first release that replaces upstart with systemd for standard boot and service manager. With systemd, [it is said](http://forums.fedoraforum.org/showpost.php?s=3f7a1442550dae472edddf3a1df9956e&p=1663756&postcount=10) that the `/etc/fstab` file no longer handles special file system, in which may have connection with the displayed error.

One of the suggestions is, to edit the `/etc/fstab` file, but I found that this is invalid workaround for host system with systemd. Instead, I tried another workaround to reinstall `initscripts` that has been mentioned in [this thread](https://bbs.archlinux.org/viewtopic.php?id=125097), but didn't solve this issue.

Above all, I can't say for sure but possibilities are: it is either a bug in 15.04 or, changes by systemd which deprecates existing method to chroot into the system.

P.S.: This is why I didn't want to test the recent releases (after 14.04) which might have broken experience because of many things, one of the things is systemd.

P.S.S: Corrected release as 15.04.

**Comment by thomasstevenson** [comment]
In case it helps, I have been using the gambas3 branch and have found it to be a bit more stable when using 15.04.

I am able to start a chroot Terminal and run commands as normal. However, running the "exit" command to exit the Terminal window throws the above error, preventing me from using any Terminal windows as in my first post.

**Comment by ghost** [comment]
@thomasstevenson 
I have been testing the 15.04 release in the virtual machine, so anything is slower on my side. Since @fluxer has pushed a commit, you might want to retry with latest Customizer from **master** branch?

**Comment by thomasstevenson** [comment]
That seems to have fixed the issue. It's been working flawlessly so far.

@clearkimura thanks for the help and kudos to @fluxer for committing the fix!

**Comment by ghost** [comment]
Confirmed the fix from my side as well.

I will mark as "Fixed" but leave this open in case you found anything else related.

**Comment by sebadiaz** [comment]
I have an ubuntu 15.10 and I experiment the same issue with the last docker image. Snif
Is anyone working to refresh it ?
