### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by AwlsomeAlex** [kamilion/customizer#107]
Hello, I would like to know the Compatibility of Customizer, and how new it is, for example, does it run and create Ubuntu 15.04 or even 15.10 BETA/ALPHA, and Does it work for Ubuntu Minimal Install (Command Line Install) Thanks, and glad to see a _working_ Remastering tool!

**Comment by ghost** [comment]
@AwlsomeAlex 
Hello! I will answer most of your questions, from **user** point of view (I'm _not_ a developer, but had been following up the development for more than several years).

You have actually raised multiple questions which require multiple answers, so make sure you are willing to read the lengthy answers and follow up promptly. Here we go.

> I would like to know the Compatibility of Customizer, and how new it is [..]

"New"..? Not really. Customizer had been tested working since Ubuntu 10.04 release. That was like, five years ago? It has been around even before Ubuntu Builder (a fork of Customizer) or relinux did, which were both discontinued last year.

> [..] for example, does it run and create Ubuntu 15.04 [..]

Short answer is yes. Issue #102 was the first feedback for Ubuntu 15.04 we had received, back in June this year. Since then, @fluxer had been pushing some fixes to make Customizer work with newer than 14.04 release.

> [..] or even 15.10 BETA/ALPHA, [..]

Short answer is maybe. We lacked of feedback from users, so we can't tell whether it works or not. Although I am both a user and tester, but I don't ever use or test Ubuntu since 10.10 release. I have been testing with Xubuntu, until 14.04 release only.

It all depends on the changes being made to the Ubuntu ISO image. The 15.04 release support was initially broken, following drastic changes in Ubuntu i.e. "systemd has replaced upstart as the standard boot and service manager"--quoted from [this release notes](https://wiki.ubuntu.com/VividVervet/ReleaseNotes).

> [..] and Does it work for Ubuntu Minimal Install (Command Line Install) [..]

Thing is, you must have an ISO image to do remastering in Customizer. What do you mean by "Ubuntu Minimal Install (Command Line Install)"? If you mean the mini ISO image, it doesn't work. For list of supported images, refer to [this Wiki page](https://github.com/clearkimura/Customizer/wiki/Supported-images).

**Additional reply**

> [..] glad to see a _working_ Remastering tool!

It is working, at least for now. But we wouldn't know how much longer this project will work with Ubuntu, seeing many changes happening in Ubuntu development recently.

As far as I know, Customizer is the only remastering tool with graphical front-end that has been working well, since 2011 to this date. Alternatively, you may resort to [manually remaster Live CD](https://help.ubuntu.com/community/LiveCDCustomizationFromScratch).

**Remarks**
I must admit that the [FAQ page](https://github.com/clearkimura/Customizer/wiki/FAQ) is missing this question. I shall add this "compatibility" question soon.

**Comment by kamilion** [comment]
Howdy!

#108 should fix up any lingering issues with the ISO filesystems of ubuntu-mini-remix, as well as lubuntu, xubuntu, and other 'official' seeds provided by canonical. 

Having a working squashfs is up to the user's skill. 
(This is where the asterisk about systemd and friends comes into play.)

I have personally tested 14.04, 14.10, 15.04, and 15.10 Beta 1 versions of Lubuntu AMD64.

I don't think it will work for "Ubuntu Minimal Install (Command Line Install)", it seems you're referring either to an 'alternative' .ISO or ubuntu-server ISO using debian-installer instead of the graphical Ubiquity installer on most of the LiveCD Desktop ISOs. I'm honestly not sure if the 'casper' live environment is used on these ISOs; often they are simply a package repository and a minimal rootfs.

It should be noted, Ubuntu-Builder isn't receiving updates, but still works up to 15.04, at least for me on lubuntu.
Project's original URL, up until april of last year:
https://launchpad.net/ubuntu-builder
I've been using launchpad to trigger periodic rebuilds for newer releases.
https://launchpad.net/~kamilion/+archive/ubuntu/ubuntu-builder

Unfortunately, vivid was the last release it had direct support in the code for.
https://github.com/kamilion/kamikazi-deploy/blob/master/resources/buildscripts/Build.patched-for-xen
It's not terribly hard to add support for a new release, as seen in this commit:
https://github.com/kamilion/kamikazi-deploy/commit/79b8dc57fb5297ab91210b750669b92b346bee03

I believe that Ubuntu-builder was the GAMBAS3 fork to the GAMBAS2 version that Customizer once was based on.

"Recently", Customizer has been rewritten in python and QT4.
I know and prefer python much more than Bash and BASIC/GAMBAS2/3.

So, I'm switching!

... I suppose that means you can consider ubuntu-builder dead, now, after all... Huh.
On the other side -- if you look around, you can still find remastersys deb files.
Here's the most recent ones I know of, for Trusty. 
https://launchpad.net/~mutse-young/+archive/ubuntu/remastersys
But if you sign up for Launchpad, you can click the 'copy packages' button yourself, which is EXACTLY what I did for ubuntu-builder, I don't know how to edit or make .deb packages myself yet, otherwise I would have published the changes I made to the "Build" script to support the Xen hypervisor as a .deb instead of a raw file in github, copied into place after installing the original .deb from the launchpad ppa...

**Comment by AwlsomeAlex** [comment]
Thanks, but one more question. How much longer will u guys be alive for? Id hate to see this project go.

**Comment by fluxer** [comment]
@AwlsomeAlex open-source projects like this one are usually driven by volantiors, so long as there are people to report and fix existing and future issues it will prevail.

**Comment by ghost** [comment]
@AwlsomeAlex 
You seemed to misunderstand.

This project is hosted on GitHub, which means anyone can contribute or copy the source code and modify for own use. The codes won't be going anywhere.

But the contributors come and go. Contributors are making efforts depending on their capability and willingness to sacrifice time for making the project alive. It's everyone rights and freedom.

**Comment by ghost** [comment]
@AwlsomeAlex 
By the way, I have already added [new entries in FAQ](https://github.com/clearkimura/Customizer/wiki/FAQ#b-likely-asked-questions) regarding compatibility. The answer also links to the relevant issues related to supported ISO images and such.

If there is nothing else about compatibility, you can close this issue.
