### ISSUE TITLE
Ubiquity Skips User Creation

### ISSUE THREAD

**Issue by AwlsomeAlex** [kamilion/customizer#111]
Hello, I used this version of Customizer, and added Ubiquity-frontend-gtk to make it installable, and whenever I try to install it to a HDD, it skips the step of User Creation. I would also like to note that I created a user called Live for when you click Try (Ubuntu) it will allow you to access the desktop. Thanks, and if you need the iso or information for more reference, I will post it. Thanks.

UPDATE: For VirtualBox, it will skip User Creation, but for Real Hardware, it will ask to create a new user. (Could be Rufus creating a new Syslinux.) UPDATE #2: User will not be created. Also this is running LXQt and LightDM.

**Comment by ghost** [comment]
@AwlsomeAlex 
Almost no relevant information provided for troubleshooting. Too many unknowns. You should provide _relevant_ details, as simple as below.

My testing setup:
- Host: 14.04 32-bit
- VM: `virtualbox-5.0` fixed VDI disk 8GB size
- ISO image: Ubuntu Mini Remix 14.04 32-bit, minimal Xfce, LightDM GTK greeter
- Installer: `ubiquity`; `ubiquity-frontend-gtk` (2.18.8.9), `ubiquity-casper` (1.340.2)
- Result: Successful (no missing steps); Able to boot into newly installed system

Anyway I think this issue is likely upstream issues i.e. Ubuntu regular releases (15.04 and newer). Well, hopefully anyone else can test and feedback for 15.04 and newer. I won't bother testing newer releases since those give mostly broken experience.

P.S.: If you use LXQt which depends on Qt libraries, why bother installing Ubiquity GTK frontend? Install its Qt-frontend instead. This may not be an issue by itself though.

P.S.S.: The VM support has some influence over the guest system experience. So if you want to run newer release like 15.04, should use newer version of VM like VirtualBox 5.0.

Added screenshot below as proof.
![test-vm-trusty-remix-install](https://cloud.githubusercontent.com/assets/1223304/10288467/9df16402-6bcb-11e5-9c09-64f3c09fdf09.png)

**Comment by clearkimura** [comment]
@AwlsomeAlex 
> [...] if you need the iso or information for more reference, I will post it.

Absolutely. Please provide relevant information and include/update in the first comment. Without relevant information, anyone can only guess and no useful feedback may be given.

**Comment by ghost** [comment]
This issue shall be closed for the following reasons:

1. it has been more than one year since this issue was reported, but there has been no similar issue reported by other users until now (fail to reproduce issue);

2. this issue may be specific to LXQt, or only apparent when used with combination of LXQt and other program (issue is not caused by Customizer; Ubiquity works as expected for Xfce in VirtualBox);

3. LXQt is an ongoing project that will replace LXDE in the future and is considered experimental and yet to see any stable release; Even [Lubuntu/LXQt wiki](https://wiki.ubuntu.com/Lubuntu/LXQt) itself has mentioned it is **known to fail** when testing LXQt (using experimental packages that has nothing to do with Customizer)

Above all, "ubiquity skips user creation" does not apply to other users.
