### ISSUE TITLE
Unable to locate package linux-signed-generic

### ISSUE THREAD

**Issue by winhex** [kamilion/customizer#120]
Hi! I have tried to customize the image of Xbuntu 14.04 32 bit and Ubuntu Mini Remix 14.04 32 bit always get this error:
`sudo customizer -r
- Read Configuration file: /etc/customizer.conf
- Rebuilding ISO...
  => Checking
  => Doing sanity checks
  => Gathering information
  => Cleaning up
  => Re-installing kernel
  Reading package lists...
  Building dependency tree...
  Reading state information...
  Package 'linux-image-3.13.0-24-generic' is not installed, so not removed
  Package 'linux-image-3.13.0-24-lowlatency' is not installed, so not removed
  Package 'linux-image-extra-3.13.0-24-generic' is not installed, so not removed
  Package 'linux-image-extra-virtual' is not installed, so not removed
  Package 'linux-image-generic' is not installed, so not removed
  Package 'linux-image-generic-lts-quantal' is not installed, so not removed
  Package 'linux-image-generic-lts-raring' is not installed, so not removed
  Package 'linux-image-generic-lts-saucy' is not installed, so not removed
  Package 'linux-image-generic-lts-trusty' is not installed, so not removed
  Package 'linux-image-generic-pae' is not installed, so not removed
  Package 'linux-image-lowlatency' is not installed, so not removed
  Package 'linux-image-lowlatency-pae' is not installed, so not removed
  Package 'linux-image-server' is not installed, so not removed
  Package 'linux-image-virtual' is not installed, so not removed
  0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package linux-signed-generic
- SUBPROCESS: Command '['/usr/sbin/chroot', '/home/FileSystem', 'apt-get', 'install', '--yes', 'linux-signed-generic', '-q']' returned non-zero exit status 100
  `

Even if I try to rebuild the original image without any changes, I get this error. I spent a lot of time to create his own image - help solve the problem.

Host system is Xubuntu 16.04 32 bit

**Comment by ghost** [comment]
Since I couldn't leave this issue go unnoticed, I will explain what the error is telling. 

> SUBPROCESS: Command '['/usr/sbin/chroot', '/home/FileSystem', 'apt-get', 'install', '--yes', 'linux-signed-generic', '-q']' returned non-zero exit status 100 `

The quoted line of error reveals that you are using Customizer from [the forked repo](https://github.com/kamilion/customizer).

**Short explanation**

To solve the error, refer to [this issue 5 on forked repo](https://github.com/kamilion/customizer/issues/5).

**Long explanation**

The original and forked repo has some differences; One of those is the default kernel installation.

While both repositories support 14.04 releases, this original repo has been optimized for 32-bit ISO builds. In contrast, the forked repo gives priority to 64-bit builds that often requires signed kernel image to boot on EFI-capable machines. For proof, see [this commit on forked repo](https://github.com/kamilion/customizer/commit/afafaf0fff3e2d3c4922357b979cf84190e706a0).

The difference is found in the `src/rebuild.py` source file.

[The source file from original repo](https://github.com/clearkimura/Customizer/blob/master/src/actions/rebuild.py), see `linux-image-generic` between line 123 and 129:

```
    detect_boot()
    if not vmlinuz:
        message.sub_info('Re-installing kernel')
        misc.chroot_exec(('apt-get', 'purge', '--yes', 'linux-image*', '-q'))
        misc.chroot_exec(('apt-get', 'install', '--yes', \
            'linux-image-generic', '-q'))
        misc.chroot_exec(('apt-get', 'clean'))
```

[The source file from forked repo](https://github.com/kamilion/customizer/blob/master/src/actions/rebuild.py), see `linux-signed-generic` between line 135 to 141:

```
    detect_boot()
    if not vmlinuz:
        message.sub_info('Re-installing kernel')
        misc.chroot_exec(('apt-get', 'purge', '--yes', 'linux-image*', '-q'))
        misc.chroot_exec(('apt-get', 'install', '--yes', \
            'linux-signed-generic', '-q'))
    misc.chroot_exec(('apt-get', 'clean'))
```

Above all, this issue is irrelevant for users of this original repo (You are reporting at wrong repo). Therefore, this issue will be marked as "invalid".

**Comment by winhex** [comment]
Many thanks you for detailed answer. Now I understand this problem and  now I know that I could use the stable version without any problems. 
Thank You for this great tool!
