### ISSUE TITLE
Change kernel of an iSO

### ISSUE THREAD

**Issue by henriqueribeiro** [kamilion/customizer#140]
Hello guys,

I have a newbie question...
How can I change the kernel inside the ISO that will be installed on a machine? I trying through chroot but without success...

Thanks in advance

Edit:

Thanks for the quick reply @clearkimura 

I have tried a naive approach with these commands:
`sudo apt-get install linux-headers-3.13.0-85-generic linux-headers-3.13.0-85 linux-image-3.13.0-85-generic`

and then 
`sudo update-grub`

I was expecting after this, that in the installation of the generated ISO I could choose which kernel I wanted.

**Comment by ghost** [comment]
Hi, there!

Make sure you are using this repo a.k.a. "old stable" (clearkimura/Customizer), and _not_ the fork (kamilion/customizer). Because each will install different kernel by default (issue #120 earlier).

If you are indeed using "old stable", then **please edit your comment and include steps you had tried** for "trying through chroot but without success".

At least I can try to identify what was wrong, before suggesting other ways.

I look forward to your feedback, thanks.

P.S.: The "steps you had tried" are still important for contributors to understand how newbies do remastering. By having such feedback, relevant suggestions could be noted for future contributors.

**Comment by ghost** [comment]
@henriqueribeiro 

> ... and then `sudo update-grub` ... I was expecting after this, that in the installation of the generated ISO I could choose which kernel I wanted.

Do you mean the GRUB boot menu, like the following screenshot?

![xubuntu-boot-local-2c](https://cloud.githubusercontent.com/assets/1223304/19996463/ae58cde2-a29a-11e6-8d46-30d3cded3189.png)

If you are indeed expecting that, then the brief answer is: **No, you can't**.

**Why not that**

In general, GRUB boot menu can be seen _after_ you do installation to a local disk, regardless of using 32-bit or 64-bit ISO image. But when using as Live media, you will see:
- SYSLINUX boot menu for 32-bit ISO image
- GRUB boot menu for 64-bit ISO image

It can be done similarly using SYSLINUX, like what Debian does. Both PAE and non-PAE kernels are included in Debian Live ISO image, which will allow booting into respective machines.

If you boot using Debian Live CD, you will see something like the following screenshot.

![jessie-xfce-boot-live-1c](https://cloud.githubusercontent.com/assets/1223304/19997043/a8ef5c1e-a29e-11e6-82c4-102a756d3faa.png)

If you want to know details, then you have to look at somewhere else. We don't provide remastering advices here, and this has been covered by [FAQ on our wiki](https://github.com/clearkimura/Customizer/wiki/FAQ).

**Remarks**

Although this is off-topic, I want to point out several things:
- In chroot environment, you won't need `sudo` command; Just type `apt-get install [package]` and always type `exit` to finish.
- Unless you want to save disk space, running `apt-get install linux-generic` will install the latest Linux kernel; Why is this so? Run `apt-cache depends linux-generic` for clue.

Above all, did I answer your question?

**Comment by ghost** [comment]
This issue shall be closed for the following reasons:

1. it has been more than two weeks since this issue was opened, but no follow up to confirm whether the question been answered or not answered;

2. this issue is more towards a question for customization in remastering process (showing multiple kernels when booting rebuilt ISO image that has nothing to do with Customizer and its features; The same question could be asked when using other remastering tool) 

Despite remastering advices are off-topic, the question is assumed to have been answered.
