### ISSUE TITLE
current LTS versions to PPA 

### ISSUE THREAD

**Issue by kisst** [kamilion/customizer#149]
http://ppa.launchpad.net/customizer-dev-team/stable/ubuntu/dists/
vs.:
https://wiki.ubuntu.com/Releases

Both 14.04 and 16.04 is missing from the PPA

**Comment by ghost** [comment]
The PPA stable for Customizer has been unmaintained since 2012, when 3.2 releases were still around at the time. The following screenshots are showing current status on Launchpad.

**PPA stable as 15 Dec 2016**

![ppa-stable-stat-20161215](https://cloud.githubusercontent.com/assets/1223304/21214135/c8048804-c2d3-11e6-87b7-61cec6b86dc8.png)

**PPA devel as 15 Dec 2016**

![ppa-devel-stat-20161215](https://cloud.githubusercontent.com/assets/1223304/21214150/e3714e9c-c2d3-11e6-9e71-ce34824b10d8.png)

I am unsure what PPA maintainer is up to (perhaps occupied with other projects). Although, the PPA maintainer seems to have been keeping the code (not binary) on Launchpad up to date as noted by the Bazaar branch listing: https://code.launchpad.net/customizer

If you still insist to use PPA, there are two suggestions I can think of:

1. Try to contact the PPA maintainer and enquire the maintainence status for Customizer PPA; perhaps by sending email to address mentioned in [this profile on Launchpad](https://launchpad.net/~eloaders) or [this profile on GitHub](https://github.com/eloaders)?

2. Use untrusted PPA by Sonicwalker, whose recipe was created using the source by PPA maintainer. [The recipe](https://code.launchpad.net/~sonicwalker/+recipe/customizer-sonicos-dev) seems to contain binary builds for currently supported Ubuntu releases.

I merely suggested above without any guarantee, and the choice is yours.

Otherwise, I have implemented [INSTALL](https://github.com/clearkimura/Customizer/blob/master/INSTALL) script to make installation easier for "old stable". See #141 for ongoing test results and discussion related to the script.

**Comment by kamilion** [comment]
As I'm a longtime ubuntu developer ( https://launchpad.net/~kamilion ), I'll go ahead and create a new PPA.

PPA Now exists (but empty as of this writing) at:
https://launchpad.net/~kamilion/+archive/ubuntu/customizer
A package has been signed and uploaded, by the time anyone ends up reading this, packages for precise, trusty, vivid, xenial, yakkety, and zesty are in the queue to be built and published.


Of note, next to it is my PPA of the GAMBAS3 ubuntu-builder, which also is still operational.
https://launchpad.net/~kamilion/+archive/ubuntu/ubuntu-builder
It is what I used before discovering the python port of Customizer.

**Comment by kisst** [comment]
```
kisst@X260:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
kisst@X260:~$ dpkg -l | grep customizer
ii  customizer                                    4.1.3-0+20170126-ppa                          all          Ubuntu Live CD remastering tool
kisst@X260:~$ sudo customizer-gui 
* Read Configuration file: /etc/customizer.conf
* Read Configuration file: /etc/customizer.conf
* Read Configuration file: /etc/customizer.conf
* Read Configuration file: /etc/customizer.conf
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x14f
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0xb5
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x3200011
```

Solution could be something like what @gkovacs did at unetbootin https://github.com/unetbootin/unetbootin/commit/75fd9f326aa00688c1a4a72e9ff70b09dad1c99e

**Comment by ghost** [comment]
@kisst 
Workaround is to use `export QT_X11_NO_MITSHM=1` as suggested by helpful end user, which was feedback about one year ago (see #116 for proof). Probably affecting GNOME or similar environment only, as I have never seen such error in Ubuntu, Kubuntu, Xubuntu.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.
