### ISSUE TITLE
Rebuilding iso live from previous status

### ISSUE THREAD

**Issue by danjde** [kamilion/customizer#152]
Hi Mubiin Kimura,
I would know if Customizer, can rebuild a new iso from a previous state of the same live build.
For example, if I make a runnable custom iso using Customizer, can I, six month later update all packages of the same iso, without rebuilding a new distro, simply from chroot environment?

many  thanks( and Good New Year ;-))

Davide
Italy

**Comment by ghost** [comment]
@danjde 
Hi, there. Yes, it can. It is one of the features that differentiates Customizer from other remastering tools; This has been a feature from before. Our wiki has mentioned that in [Features] page.

> D. Hidden features
> ...
> 2. Continue from last time
> 
> Even Customizer GUI is closed, existing work will remain unchanged as long as «Clean» button is not clicked. The user can continue from last time immediately at next run.
> 

Load an ISO then leave it, and Customizer will preserve the state. Meanwhille, you can't load another ISO without discarding currently loaded ISO. This is because Customizer limits to only one instance at a time (This limitation is due to issue #74 that was discovered some time ago).

If there is no further question, you can close this issue.

[Features]: https://github.com/clearkimura/Customizer/wiki/Features

**Comment by ghost** [comment]
This issue shall be closed, since there is no feedback for the past 3 weeks. The question has been addressed and assumed to have been answered.

From now on, please use official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
