### ISSUE TITLE
DE choice in "Desktop" 

### ISSUE THREAD

**Issue by sylviette** [kamilion/customizer#156]
Hi,

I'm not sure it's the best place to write, in case, please, move to the right place ;-)

Two questions, more than issues:

1) if I expand a iso with 3.xx version (gambas version) and then manage it with 4.xx version for building with 3.xx again (It happened to me with 4.0.0 that gave errors while building), then is impossible to get access to IDE in iso, as if it doesn't create any user.

2) in gambas version there was the DE choice, in case of multiple DEs, I mean: choosing "Desktop" it asked which DE you wanted to use; how can I do the same in 4.0.4 version?

Thanks and regards,

Sil

**Comment by ghost** [comment]
@sylviette 
Replied as below.

> I'm not sure it's the best place to write, in case, please, move to the right place ;-)

Since commit 521f544 that was pushed in late November 2016, you can run `customizer --version` to check for "Customizer X.Y.Z (old stable)". If you are using "old stable", this is the right place to ask.

> Two questions, more than issues:

I think your questions have typos or errata?  Did you mean "IDE" (Integrated Development Environment, a programming tool) or "DE" (Desktop Environment)? I guess the latter, since "Desktop" was mentioned? Also, we never had version 4.0.0 or 4.0.4, because the first release after rewritten in Python is 4.1.0. Not sure which version are you talking about here... See [release tags](https://github.com/clearkimura/Customizer/tags) for proof.

> 1. if I expand a iso with 3.xx version (gambas version) and then manage it with 4.xx version for building with 3.xx again (It happened to me with 4.0.0 that gave errors while building), then is impossible to get access to IDE in iso, as if it doesn't create any user.

Without telling what errors were you seeing, it is impossible to tell anything. Besides, it is never good to mix between `gambas3` and `master` branches. This will complicate the matter and will waste more efforts when troubleshooting.

I had briefly looked at the source code and commit history, and I believe 3.x release from `gambas3` and 4.x release from `master` are *not* compatible with each other. As a proof for incompatibility, last remix that I had created using 3.x is 12.04 remix ISO and that cannot be extracted using 4.x release.

> 2. in gambas version there was the DE choice, in case of multiple DEs, I mean: choosing "Desktop" it asked which DE you wanted to use; how can I do the same in 4.0.4 version?

The short answer is, someone needs to fix or implement that.

The long answer is, most of things "just work" in 4.x release. It currently handles few things automatically, which may bother some users. I think no user has filed an issue to complain that, so I decided to remain silent and continue studying the source code.

For example, if I install multiple text editors, "Edit sources" button will run the last detected text editor found in the array list. Mousepad is found first in the array list, but when I had installed Gedit that appears later in the array list, then Gedit is used by Customizer.

The automated behaviour is somewhat less desirable, but this will only happen if user choose to install few applications of same kind (not only text editor, but also file manager, terminal emulator, and may be others in source code). Normal users running with default setup wouldn't notice this limitation.

**Next action**

> in case of multiple DEs, I mean: choosing "Desktop" it asked which DE you wanted to use

For "old stable" release, the priority to fix the "Desktop" feature is quite low at the moment. Because this feature is also related to other features i.e. Edit sources, Terminal that shares similar behaviour and issue, it will take some time to come out with a standard way to solve.

Please leave a comment under #119 and suggest that, so I can consider and look into the matter in next milestones (after 4.1.5). Thanks.

Finally, if you have no further questions to clarify, you can now close this issue.

**Comment by sylviette** [comment]
OK, thanks for answering. And yes, I meant DE, not IDE (there, I'm using Lazarus and QT5)

Sil
