### ISSUE TITLE
Rebuilding kernel 4.15 faisl

### ISSUE THREAD

**Issue by phlmm** [kamilion/customizer#191]
Rebuild iso initrd fails with 

gzip: /boot/initrd.img-4.15.0-13-generic: not in gzip format
cpio: premature end of archive
* SUBPROCESS: Command '/usr/sbin/chroot /home/customizer/FileSystem zcat /boot/initrd.img-4.15.0-13-generic | cpio --quiet -id conf/uuid.conf' returned non-zero exit status 1

The file type appears to have changed:

/boot# file initrd.img-4.15.0-13-generic 
initrd.img-4.15.0-13-generic: ASCII cpio archive (SVR4 with no CRC)

**Comment by kamilion** [comment]
Sorry, that appears to be a problem within the ISO you're rebuilding, not something that can be fixed in customizer.

It's not a problem I've seen while developing the kamikazi-core buildscripts on top of Customizer either.
https://github.com/kamilion/kamikazi-core/tree/master/buildscripts/xenial

I get successful builds of 14.04, 16.04, and now 18.04, using the lubuntu source media.

If you want to provide more information, such as the source media you're using (Looks like 16.04-hwe to me, so 16.04.4 ISO at least) and what buildbox is being used, reopen the issue, and I can attempt to help.
