### ISSUE TITLE
The customizer does not seem to support the Ubuntu server

### ISSUE THREAD

**Issue by scott-yao2018** [kamilion/customizer#214]
When I loaded the ISO file, it failed, when I used the file "ubuntu-16.04.1-server-amd64.iso", I then used the file " ubuntu-16.04.6-desktop-amd64.iso" instead , it successed. 
So why?

**Comment by scott-yao2018** [comment]
![Critical_087](https://user-images.githubusercontent.com/43429623/66388118-09f93900-e9f8-11e9-820b-35be1ce147ef.png)

**Comment by TheLastDragonrider** [comment]
Same issue with Ubuntu-18-04.3-server-amd64.iso (Ubuntu 18.04 server). Desktop variant works.

**EDIT**
@scott-yao2018 Found our problem:

"You didn't read the first guide

You attempt to remaster the alternate, mini and server ISO images, which are unsupported."

Found on Common Mistakes:
https://github.com/kamilion/customizer/wiki/Common-mistakes

Also:

"ISO image compatibility
For 12.10 and newer releases of Ubuntu ISO image, use at least Customizer 4.1. For 15.04 and newer releases, use the latest Customizer 4.1.1 (as commit 2a7864f). Other ISO images such as alternate, server and minimal are different and unsupported."

Found on:
https://github.com/kamilion/customizer/wiki/Supported-images

**Comment by scott-yao2018** [comment]
Sorry, I over look it. This issue is closed.

**Comment by kamilion** [comment]
>So why?

Server images do not rely on the initramfs-tools + casper scripts, which customizer relies on for live ISO startups.

At some point I *may* be able to add support for the server-live variants that 18.04 provides -- we'll see what 20.04 LTS's layout looks like, and if it continues the 18.04 trend, I'll add support. If they do something different yet again from 18.04 -> 20.04, then it's probably going to be too much work for me to try to rearrange all the code to support all the variations, and we'll have to stick with the desktop ISO requirement.

If you'd like to generate your own server installers, look at Packer, debos, or virt-builder for wrappers around debootstrap. Generally you're not going to be able to build *ISOs* though, because that's not what debootstrap does. You'll get images for various cloud services, VMWare, or Virtualbox, which can also be deployed to bare metal servers or a local openstack or kubernetes instance.
https://packer.io/
https://lwn.net/Articles/758461/
https://www.collabora.com/news-and-blog/blog/2018/06/27/introducing-debos/
https://github.com/go-debos/debos
http://libguestfs.org/virt-builder.1.html

These are also extremely popular for building images for non X86_64 hardware, such as raspberry pi2+ or other single-board-computers, and none of those systems can boot ISOs or CDs anyway, so building an installation medium just doesn't make any sense these days.

Hope that assists in helping you learn what's out there and more importantly, *why* it's out there.

If you're looking for a specific use case outside of the x86_64 space, feel free to track me down on IRC or email me, as I primarily work in embedded systems these days and can assist you in enumeration of your deployment options.

**Comment by kamilion** [comment]
Oh, one thing I should point out.

If all you're looking for is an ISO without graphic mode, you can make this change on a desktop source ISO of your choice:

```bash
# Disable the GUI on boot to allow another script to start it later at boot, or not at all.
cd /lib/systemd/system
# Change the default boot target to multi-user.target from graphical.target
ln -sf multi-user.target default.target
```
From: https://github.com/kamilion/kamikazi-core/blob/master/buildscripts/bionic/25-apply-filesystem-mods.sh#L7-L10

And then optionally purge all the graphics packages, along with X/Wayland entirely to shrink the size.
More or less, this is what the Ubuntu Mini Remix ISO is/was, if you can even find a copy of it anymore.

**Comment by scott-yao2018** [comment]
Thanks a million to kamilion for your helpful answer, it's a strong possiblity that I'll bother you with other questions later on.
