### ISSUE TITLE
run 2 instances...

### ISSUE THREAD

**Issue by mitsuzero** [kamilion/customizer#38]
can run 2 instances... or 2 projects at the same time? ...

**Comment by fluxer** [comment]
Unless you change to scripts and GUI - no. What's the reasons?

**Comment by mitsuzero** [comment]
i want to work in 2 diferent projects, but now ... only can work with one.. they have 2 Dif DE...

**Comment by fluxer** [comment]
I'm sorry, but this is not possible, nor will it be. At least I'm not gonna implement this. Feel free to do it yourself and make pull request.

**Comment by mitsuzero** [comment]
ah! it's OK... and thanks for the fast reply ... your work is amazing..

**Comment by ghost** [comment]
@mitsuzero 
I have few suggestions for workarounds:

**Method 1**
The obvious way is, you must have two PC running Customizer on each.

**Method 2 (Doesn't work for Customizer)**
If you have only one PC, you create two user accounts on it.
Login the first user account and run first Customizer, load first ISO.
Later, switch to second user account and run second Customizer, load second ISO.

**Method 3**
Again, if you have only one PC and Method 2 fails, you still can have Customizer on host PC and another Customizer on guest PC (virtual machine).
- Pros:   If you have two monitors connected to single PC, you can view Customizer on host PC on one side, and another Customizer on guest PC on another side.
- Cons:  Running virtual machine can consume a lot of host PC resources--requires powerful PC. Worst case, your virtual machine will be less powerful than your host PC, depending on settings.

**Edit** Updated this comment; Method 2 doesn't work for Customizer, although some other applications such as Thunar file manager allows multiple instances. Tested in Xubuntu 14.04 host system.

**Comment by mitsuzero** [comment]
hoo.. :) ok!.. im proceding with the suggestion, whatever is the result i
post it .. i reply to you knowledge :)

2013/12/16 clearkimura notifications@github.com

**Comment by ghost** [comment]
This issue shall be closed for the following reasons:

1. it has been almost three years since this feature request was made, but there has been no feedback and no pull request being made to implement "run two instances";

2. running multiple instances is known to introduce issues, such as issue #74 that caused either one of two instances of program to crash when trying to customize using "Desktop" feature in Customizer;

3. running multiple instances will likely consume significantly higher memory usage and higher processor load, thus leads to wasteful resources

For above reasons, it may be a useful feature to have but that will require more resources to run, further complicate the remastering process and potentially troublesome to debug issues.

**Alternative implementation**

There are programs i.e. Grsync, Quarry that implement "multiple profiles" that is *not* "multiple instances", which still limited to running only one instance. This has been hinted by issue #112 that suggested "multiple projects". But that is another ambiguous request.
