### ISSUE TITLE
Documentation clean up

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#86]
**Revised on 2016.03.27**

Documentation clean up is an ongoing effort and expected to finish soon (completed 2016.03.27).

**Note to myself: Don't explain much in Wiki! Just explain in simple way, enough for users to follow. Steps should work and can be reproduced by anyone.**

---

**Clean up status** `ok` : satisfactory  `--` : onhold    `x` : deprecated   `%%%` : messy

`!` Each of these articles (Definition, Rebranding, Remastering) should contain featured content navigation like Wikipedia, which links to all three articles (except the currently viewing article shall be bolded and unlink), which will promote discovery and encourage reading (done on 2016.03.21).

**Wiki**
`ok` Sidebar
`&` `ok` [Home](https://github.com/clearkimura/Customizer/wiki) 
`ok` [Archive](https://github.com/clearkimura/Customizer/wiki/Archive) --- now simplified; since mentions are already documented by date (from top: newest to oldest); Separation by releases are redundant after all (why I didn't notice this earlier)?
`x` Changes log 
`ok` [Choosing Python over Gambas](https://github.com/clearkimura/Customizer/wiki/Choosing-Python-over-Gambas)
`ok` [Common mistakes](https://github.com/clearkimura/Customizer/wiki/Common-mistakes)
`ok` [Contribute](https://github.com/clearkimura/Customizer/wiki/Contribute)
`x` Credits
`!` `ok` [Definition](https://github.com/clearkimura/Customizer/wiki/Definition)
`ok` [Developer notes](https://github.com/clearkimura/Customizer/wiki/Developer-notes) --- now legacy (probably won't get updated anymore)
`ok` [Different images](https://github.com/clearkimura/Customizer/wiki/Different-images)
`ok` [FAQ](https://github.com/clearkimura/Customizer/wiki/FAQ)
`&` `ok` [Features](https://github.com/clearkimura/Customizer/wiki/Features) --- now with optional screenshots (explain well in text, enhanced by screenshots);

There is no accurate guide for UI elements in documentation. Known suggestions below:
- don't use ` (grave accent) for other than codes and command line
  - good: `sudo apt-get update`
  - bad: `Application` > `Internet` > `Firefox`
  - alternative: **Application > Internet > Firefox**
- don't use `<kbd>` for UI elements, use "this" or **this** instead;
  - good: <kbd>Ctrl</kbd>+<kbd>Enter</kbd>
  - bad: <kbd>Close</kbd> button
  - alternative: "Close" button, **Close** button, «Close» button (rationale at below)
- then again, don't overuse formatting to indicate different UI elements i.e. tabs, buttons, labels;
- such elements shall continue to use text;
  - no format: Main tab, Open button, FileSystem directory
- and perhaps highlight the label of element;
  - format 1: "Main" tab, "Open" button, "FileSystem" directory
  - format 2: **Main** tab, **Open** button, **FileSystem** directory
- alternative formatting by using Unicode 1.1 characters:
  - symbol 1: ［Main］tab, ［Open］button, ［FileSystem］directory (U+FF3B, U+FF3D)
  - symbol 2: «Main» tab, «Open» button, «FileSystem» directory (U+00AB, U+00BB)
  - symbol 3: »Main« tab, »Open« button, »FileSystem« directory (variant of symbol 2)
  - symbol 4: ⌜Main⌟ tab, ⌜Open⌟ button, ⌜FileSystem⌟ directory (U+231C, U+231F)
- even with Unicode 1.1 characters (supposedly the most compatible characters), some mobile system doesn't fully support certain characters i.e. symbol 4 and shows rectangle boxes instead
- using "quote" or **bold** is likely less suitable than using special characters of Unicode, except for convenience and faster to type
  - the "quotes" are usually used to bring a string of words together to explain something
  - the **bold** is like _italics_ to give emphasis to certain keywords in general
  - the UI elements are not just "string of words" or **keywords**, but also the keys to user interactions for using a program that runs on computer
  - «Close» button is likely more meaningful, instead of "Close" button or **Close** button (this is suggested for use on GitHub Wiki; However, "quotes" or **bold** would be more convenient and faster to type for generic use)
- using «double brackets» (a.k.a [guillemets](https://en.wikipedia.org/wiki/Guillemet), a type of quotation marks rather than brackets) are likely good choice for three reasons:
  1. effectively distinguish label text from description text (known usage: to indicate "field" in word processor or e-mail markings);
  2. legible even without spacing;
  3. promotes continuity when reading on screen
     - continuous: «first» tab, «second» button, «last» directory
     - distractive: ［first］tab,［second］button,［last］directory
- the UI navigation is another headache:
  - symbol 1: **Application > Internet > Firefox** (U+003E, misleading use yet generic)
  - symbol 2: **Application : Internet : Firefox** (U+003A, alternative)
  - symbol 3: **Application → Internet → Firefox** (U+2192, used similarly in Xubuntu manual except emphasized by **_bolded italics**_ and the arrows may be styled using fonts and CSS, which cannot be achieved using Markdown)
  - symbol 4: **Application » Internet » Firefox** (U+00BB, reuse from earlier examples)
  - symbol 5: **Application ‣ Internet ‣ Firefox** (U+2023, like breadcrumb used in modern Windows, Ubuntu manual also uses this)
- while the symbol 3 and 4 may be common, these would look very small and your eyes need to squint (when viewing from desktop, but legible from mobile); symbol 2 is uncommon in my reading experience
- so remaining symbol 1 and 5; If possible, I'd pick symbol 5 (of course, symbol 1 would be more convenient and faster to type) but symbol 5 has few variations:
  - this type: ‣ U+2023 BLACK RIGHT-POINTING SMALL TRIANGLE
  - this type: ▸ U+25B8 TRIANGULAR BULLET
  - this type: ▶ U+25B6 BLACK RIGHT-POINTING TRIANGLE
  - this type: ► U+25BA BLACK RIGHT-POINTING POINTER
- even available since Unicode 1.1, none of these variations are supported properly on mobile platform; Then symbol 1, 3, or 4 would actually qualifies for best compatibility.
- apparently some symbols are rendered different in size or style, due to font preferred by the web page and not that is specified by web browser;
- then, symbol 3 → is likely good choice and logically means "if...then"; So this is preferred for Wiki and probably user guide also

`ok` [First guide](https://github.com/clearkimura/Customizer/wiki/First-guide) --- now concise and short enough already
- reduced text from 85 to 52 lines; [this compare revisions](https://github.com/clearkimura/Customizer/wiki/First-guide/_compare/d52750609c889195805296e5f13400b928cc51be...764fcdb0c3a6e99e366bef9455c323a38dd25d0c)
- but later increased to 54 lines due to minor revision to text order; [last compare revisions](https://github.com/clearkimura/Customizer/wiki/First-guide/_compare/764fcdb0c3a6e99e366bef9455c323a38dd25d0c...df7e4d6dd9fbfe52788dfdb69c15e8220df54c7d)
- linked to "FAQ", in case user in doubt
- linked to "Feature" page, on how to configure and use Customizer

`ok` [Help for 14.04](https://github.com/clearkimura/Customizer/wiki/Help-for-14.04)
`ok` [Installation](https://github.com/clearkimura/Customizer/wiki/Installation)
`ok` [Issue submission](https://github.com/clearkimura/Customizer/wiki/Issue-submission) -- now at simplest; Keep good examples as guideline.
`ok` [Logos](https://github.com/clearkimura/Customizer/wiki/Logos) -- quoted in issue 115 
`ok` [Manuals](https://github.com/clearkimura/Customizer/wiki/Manuals)
`ok` [Minimalist ISO](https://github.com/clearkimura/Customizer/wiki/Minimalist-ISO)
`!` `ok` [Rebranding](https://github.com/clearkimura/Customizer/wiki/Rebranding) -- now ease of reading for either impatient users or curious users 

`!` `ok` [Remastering](https://github.com/clearkimura/Customizer/wiki/Remastering)
- some contents from "First guide" will be moved to here
- this will be my third and the last article to be written for this project (done on 2016.03.26)

`ok` [Screenshots](https://github.com/clearkimura/Customizer/wiki/Screenshots) `&`
`ok` [Supported host systems](https://github.com/clearkimura/Customizer/wiki/Supported-host-systems)
`ok` [Supported images](https://github.com/clearkimura/Customizer/wiki/Supported-images)
`ok` [Tutorials](https://github.com/clearkimura/Customizer/wiki/Tutorials) -- no changes in order, simplified headings

**Repository**
`ok` [Customizer: Master branch](https://github.com/clearkimura/Customizer) (limited to documentation related files i.e. Contributors, README.md)
- Contributors: check recent contributors, which are missing from the list (done on 2016.03.26)
- README.md: to mention CLI doesn't take arguments after the option (questioned long time ago);
- or should this be mentioned elsewhere in Wiki instead (yes, mentioned in "First guide")

`x` CustomizerMedia
- Copied and renamed most files `&` to Dropbox storage
- This "CustomizerMedia" repository will be **deleted permanently** (done on 2016.02.05)

`ok` Dropbox
- this has been a shared location to keep copies of backup for Customizer releases and early documentation i.e. user guide 3.x;
- bandwidth limit allowed per month by Dropbox is basically 10x more than GitHub (should be more than enough to handle user visits).

---

**Original thread**

Some important things to clarify beforehand:
1. is **gambas3** branch still relevant?
   - if no, I plan to remove from Wiki main page and move to **Archive** page
2. for **master** branch, which install method is recommended (or which order):
   - using old script (assume usable after I edit dependencies to suit version 4.1)
   - manual make (via README.md)
   - git clone (via FAQ)
3. for **master** branch, which launch method is recommended (or which order):
   - `pkexec` via Terminal/GUI
   - `sudo` via Terminal/GUI
   - `gksu`,`kdesu`,`kdesudo` via Terminal/GUI

Any other comment to improve documentation is welcomed.

**Comment by fluxer** [comment]
Hi,
1. Well, for me it is not. But it may be usefull to someone else in a sense that it has more features than master right now. I also keep it for historical reasons and reference on how to implement the extra features later into current master, or at least that was the plan.

From what I can tell people better not use it, the master branch has accumulated some fixes and changes that were required to support the newer Ubuntu releases thus I recommend moving on and remove the docs for it.

2. I would recommend building deb package and installing that so the package manager of the distribution (assuming Debian/Ubuntu/other apt-derived distribution) can keep track of Customizer's files.

But after all, most people do not want to deal with this and will just use the method from the README, which is the most obvious one. FAQ is fine too. Your call.

3. Ultimately, they do the same thing.

`pkexec` comes from Polkit/PolicyKit (I'm still confused about that project's name, reference to it varies) should be the most secure one since it is two layer security - first it has it's own set of policy rules and then it makes use of dbus which is also a security layer. It is recommended for GUI users but not always present on the system thus they can use `gksu, kdesu, kdesudo`, again, if they are available on the system.

`sudo` should be used only by CLI lovers, it also has its own policy configuration but is not ment for interaction with fancy (or not so) dialog boxes with input fields and such. It would be either a preference or necessity to use it due to lack of the mentioned priviledge esalators above. Sadly, it will not work as the user expects when used from .desktop file, an example:
- user installs Customizer with the following command: `make ELEVATOR=sudo && sudo make install`
- user tries to launch Customizer from menu
- user menu/screen/whatever freezes because sudo requires CLI interaction, it's stdin/stdout are on the TTY

I've seen polkit do the same when no agent is present so all in all - there isn't a perfect answer here. Stick with `pkexec`.

Cheers!

**Comment by ghost** [comment]
@fluxer
This is a follow up from question 2.

If users choose to install master branch manually (via README or FAQ), is it possible to safely remove all installation files i.e. without using package manager?

I have seen many instructions to install, but not otherwise (Ah, I suppose I can refer to your install script file as reference).

Could it be that 'manually remove installation' of any program on Linux is not advisable in general?

Sent using a Sony Ericsson mobile phone

**Comment by fluxer** [comment]
@clearkimura 

Yes, it is possible to remove it. All you have to do is call `sudo make uninstall` from the source directory of the same version you installed from. If you for an example call `uninstall` from newer version it may no longer install old files that previous one did and the rule to remove it may not be present anymore. It's not like manual remove is a bad thing, it's just that you need to be aware of how things works, that includes the software you are going to remove (it's build system) and the system you are going to do this on. That is why package managers exists.

I hope this answers your concirns.

**Comment by clearkimura** [comment]
@fluxer 
Glad to hear your opinion. After all, end users (that includes me), tend to avoid such hassles to trace manual install, although "it just works" to make program run as expected.

So I googled the Web and I found that combination of `build-essential` and `checkinstall` will do the job. These can handle `*.tar.gz` packages and converts into `*.deb` and installs it to host system, so that package manager is aware of this installation.

I have tried this method using GNU Hello program downloaded as `*.tar.gz` by using below commands, line by line.

    sudo tar zxvf hello-2.10.tar.gz
    cd hello-2.10
    sudo ./configure
    sudo make
    sudo checkinstall

The last command is normally run as `sudo make install`. But since I want to make installation aware by package manager, I need to replace with `sudo checkinstall` command.

This is so far the easiest method to handle `*.tar.gz` installation automatically.

However, I am yet to adapt this method to install latest Customizer. Will figure out soon.

**Comment by clearkimura** [comment]
The said method didn't work well for Customizer.

I had tried with following steps.

    wget https://github.com/clearkimura/Customizer/archive/master.tar.gz
    sudo tar zxvf master.tar.gz
    cd Customizer-master
    sudo make LRELEASE=true
    sudo touch tr/fake.qm
    sudo checkinstall

Initially tried with `sudo make` but issue #85 persists, so I followed the mentioned advice. Finally `sudo checkinstall` did work, but failed to build the Debian package. I estimate due to the package structure is not satisfying GNU or Debian packaging standard.

So, I ended up relying on `sudo make uninstall` command to remove it manually. No issue here, just cannot be handled by package manager as I hoped earlier. At least I tried.

**Comment by fluxer** [comment]
@clearkimura 
Well, you can create `.deb` package for Customizer:

```
wget https://github.com/clearkimura/Customizer/archive/master.tar.gz
tar zxvf master.tar.gz
cd Customizer-master
make deb
```

And then install that with `dpkg -i <path to the .deb file>`.

Cheers!

**NOTE** This method is most proper. The common practice to create package is _without_ using `sudo` according to [this Wiki](https://wiki.archlinux.org/index.php/Creating_packages_for_other_distributions).

**Comment by clearkimura** [comment]
@fluxer 
Um, I believe there is no such command as `made`. I checked as below.

    $ whatis made
    made: nothing appropriate.
    $ made
    No command 'made' found, did you mean:
    Command 'mad' from package 'mmv' (universe)
    Command 'make' from package 'make' (main)
    Command 'yade' from package 'yade' (universe)
    Command 'mame' from package 'mame' (multiverse)
    Command 'jade' from package 'jade' (main)
    Command 'maude' from package 'maude' (universe)
    made: command not found

I thought it was custom script created by you, but that was not the case either. I did try from the `Customizer-master` folder but same output as above.

What was the command you had used in last line?

**Comment by fluxer** [comment]
@clearkimura 

Right, that would be `make`. I corrected my comment above.

**Comment by clearkimura** [comment]
@fluxer 
Thanks for your clarification.

I somehow managed to resolve the latter method (using `make deb`). Initially, it didn't work because the suggested workarounds was ineffective. Later, I figured out that `qt4-linguist-tools` resolved the issue (as explained in issue #85 ). Also, I managed to figure out the problem with first method (using `checkinstall`), it was just a minor problem with package details.

The differences have been explained below:

* first method using `checkinstall` is stringent on certain package information, but it doesn't prevent user from installing with missing dependencies. In my case, `qemu-kvm` was not installed on host system but `checkinstall` proceed to install anyway.

* second method using `make deb` will look into `lrelease` and `qemu-kvm` dependencies (or any missing packages) and will quit installation with errors, until all dependencies are satisfied.

Above all, the second method using `make deb` is more proper with package details and dependencies handling. Both methods have been tested working and can be seen from package manager.

**Comment by fluxer** [comment]
@clearkimura 
I have no idea what `checkinstall` actually does. `make deb` + `dpkg -i <deb>` would be the way to go on Debian based system.

**Comment by clearkimura** [comment]
@fluxer 
You are right. The `checkinstall` method is a hackish way to create a `*.deb` package and it is not recommended for redistribution purpose, as read on the Web.

**Comment by ghost** [comment]
The "Customizer User Feedback (2015)" has been finalized and the responses have been reset to a new sheet. The new form is now accessible from [GitHub Wiki Home page](https://github.com/clearkimura/Customizer/wiki).

**Comment by fluxer** [comment]
Nice, thanks.

**Comment by ghost** [comment]
Customizer wiki on GitHub now uses a custom sidebar for eased navigation. More changes may be noticed in stages to organize the contents.

Also, I have created a new repo to keep some resources (mainly screenshots) for the Wiki. Because of this, I finally learned to use `git` for [adding images to Wiki](https://help.github.com/articles/adding-images-to-wikis/) by linking to images in repository.

I thought this is better than linking from external location, especially for lightweight files. Less the hassles to update on GitHub Wiki.

Edit: Removed link from "a new repo" text.

**Comment by fluxer** [comment]
Awesome! I did not even know that you can link images from repos :).

**Comment by ghost** [comment]
The 3.x user guide PDF and HTML files have been pushed to CustomizerMedia repo. Each can be downloaded to local machine via **raw links** (direct link will not work), which are used in [Manuals page](https://github.com/clearkimura/Customizer/wiki/Manuals). Tested from recent Firefox Web browser.

**Comment by ghost** [comment]
Brought back old content "Minimalist ISO" in [Tutorials page](https://github.com/clearkimura/Customizer/wiki/Tutorials). The content is revised edition of original, which means deprecated information has been removed and some has been updated.

**Comment by fluxer** [comment]
:+1:

**Comment by clearkimura** [comment]
@fluxer 
Just want to clarify something.. It's about the Ubuntu release versus Customizer version compatibility. From what I assume at the moment:

* For Ubuntu 12.04 and older host system, use 3.2 release, **gambas3** branch.
* For Ubuntu 12.10 and newer host system, use 4.1 release, **master** branch.

What if user insists to install 4.1 release on older host system--Ubuntu 12.04, for example? Do you support this combination?

**Comment by clearkimura** [comment]
@fluxer 
My bad. I confused myself between host system and ISO images, again!

**Comment by ghost** [comment]
The [First guide](https://github.com/clearkimura/Customizer/wiki/First-guide) page now includes updated instructions to install, run and configure Customizer from **master** branch. Alternative installation methods, including **gambas3** branch, are covered in [Installation](https://github.com/clearkimura/Customizer/wiki/Installation) page as separate (which can be linked from the First guide page as well).

Some contents in the First guide are still _in progress_ and will be updated later.

**Comment by ghost** [comment]
I won't go as far as making an official developer guide for Customizer, since I am more toward a documentation contributor and less than a developer.

So I decided to [collate notes](https://github.com/clearkimura/Customizer/wiki/Developer-notes) instead. Now accessible from the sidebar.

**Comment by fluxer** [comment]
@clearkimura 

I've added some of the things that made me work on 4.x to the page, it's not history but if I'm to write the whole thing it would take quite a lot of time because there is almost a year between 3.x and 4.x release and a lot of things have happened during that period - something I do not have the time for. I hope that helps.

**Comment by clearkimura** [comment]
@fluxer

Yes, it is still helpful to let others read and understand. It's alright,
that is still part of history ;)
Notes may accumulate, so I will organize into separate pages later.

On 27 March 2015 at 03:52, Ivailo Monev <notifications@github.com> wrote:

> @clearkimura <https://github.com/clearkimura>
>
> I've added some of the things that made me work on 4.x to the page, it's
> not history but if I'm to write the whole thing it would take quite a lot
> of time because there is almost a year between 3.x and 4.x release and a
> lot of things have happened during that period - something I do not have
> the time for. I hope that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clearkimura/Customizer/issues/86#issuecomment-86689215>
> .
>



-- 
MUBIIN
clearkimura@gmail.com

**Comment by clearkimura** [comment]
Updated [Developer notes](https://github.com/clearkimura/Customizer/wiki/Developer-notes), with content moved to separate page.

**Comment by ghost** [comment]
The [First guide](https://github.com/clearkimura/Customizer/wiki/First-guide) is more or less complete. But some linked pages from there might be updated later. The "Linux remastering help" section is now much readable in the [Tutorials](https://github.com/clearkimura/Customizer/wiki/Tutorials) page.

**Comment by clearkimura** [comment]
I am still cleaning up Wiki pages to this date, little by little. Occasionally, I look around other FOSS/FLOSS projects on how their resources are presented on the Web.

Some information:

* I hope to finish 2/3 parts by mid-2015, although this is rough estimate

* the remaining 1/3 part (the user guide), may not be written after all

* this issue will be closed as soon as Wiki pages have been cleaned up

As for the user guide, I will create a new issue as separate for open suggestions.

**Comment by ghost** [comment]
Updated [FAQ](https://github.com/clearkimura/Customizer/wiki/FAQ) and other related pages to satisfy issue #107 and similar questions in future.

**Comment by ghost** [comment]
As today, I think I have fixed most of the mess that had been done on Wiki.

The most important piece, [First guide](https://github.com/clearkimura/Customizer/wiki/First-guide) is now concise and short enough to be read. Most text and links were moved to [FAQ](https://github.com/clearkimura/Customizer/wiki/FAQ) for better discovery and further reading. [Features](https://github.com/clearkimura/Customizer/wiki/Features) now includes useful screenshots, which makes it a good alternative to the user guide 4.x.

Since this issue was opened in late January 2015, the documentation clean up continued for at least a year to this date. And I have finally finished it. Whew.

This issue is now closed for good.

P.S.: I will review the entire Wiki for one last time, to check if I had missed anything else and do minor editing if necessary. I shall do so by end of this month (within next few days).
