### ISSUE TITLE
Customizer works perfect with Ubuntu 14.04 Mate

### ISSUE THREAD

**Issue by carlossoy** [kamilion/customizer#87]
It works perfect with the version of Ubuntu 14.04 Mate
https://ubuntu-mate.org/
There is a problem. Unable to update the system and everything is broken if the libpam-systemd program is not locked.
It is necessary to block the version using Synaptic. In this way everything works perfectly smoothly.

**Comment by fluxer** [comment]
Hello,

Thank you for your feedback, much appreciated!

Can you provide more information on which version are you using? The issue with the upgrades of some packages should have been solved with 2b5e04e which dates from Sep 6 2014. Basicly, if you installed from the latest checkout of master branch you should not have this issue.

Cheers!

**Comment by carlossoy** [comment]
My version is Ubuntu 14.04 Mate. Kernel version linux-image-generic-3.13.0-46.
About two months since I returned to try a new system update with libpam-systemd unlocked ago. Perhaps in February.
A greeting

**Comment by fluxer** [comment]
So, the issue with upgrades is not solved? I will fetch the ISO image when I have some time and give it a go.

**Comment by fluxer** [comment]
As per https://bugs.launchpad.net/ubuntu/+source/upstart/+bug/430224 people solve it with diverting but it was dropped from Customizer because of other issue (see #63). https://wiki.ubuntu.com/NattyNarwhal/TechnicalOverviewUpstart does not seem to help either. In the end, AFAICT, upstart does not work well in jails. I'll leave the issue open for a few days if anyone else has something to say but I consider this not our issue.

Cheers!

**Comment by carlossoy** [comment]
Thank you very much for your work.
A greeting
Carlos.

**Comment by ghost** [comment]
As per [this earlier comment](https://github.com/clearkimura/Customizer/issues/87#issuecomment-78055486) dated Mar 10, 2015, this issue is _not_ considered as Customizer issue. Despite the limitation and nobody has left any comment for more than a year, this issue will be closed.
