### ISSUE TITLE
ImportError for module

### ISSUE THREAD

**Issue by GlassSources** [kamilion/customizer#89]
I can't find the application shortcut, so I go to the data file and go to the .desktop and get the error.

Traceback (most recent call last):
  File "/usr/sbin/customizer-gui", line 10, in <module>
    import gui_ui
ImportError: No module named gui_ui

**Comment by fluxer** [comment]
Is /usr/share/applications/customizer.desktop present on your system?
Is /usr/share/customizer  present on your system?
What's the output of `python2 -c 'import sys; print(sys.prefix)'`

What Desktop Environment are you using? What's the plugin for the menu if any? Are you using a dock application (no DE panel)?

**Comment by GlassSources** [comment]
LXDE, Unity 7, and GNOME. (Xubuntu, Ubuntu, and Ubuntu GNOME)

**Comment by GlassSources** [comment]
Gambas3 works for me, I'll just work with that.

**Comment by fluxer** [comment]
Your call.

**Comment by ghost** [comment]
Does this issue relates to the "XDG menus part, it broke again"? How odd, because I never noticed/faced this issue while running recent releases from **master** branch on Xubuntu 12.04 and 14.04 32-bit host systems. Not even once.

To answer some of @fluxer questions:

> Is /usr/share/applications/customizer.desktop present on your system?
> Is /usr/share/customizer present on your system?

Yes, for both questions.
Yes, for both Xubuntu 12.04 and 14.04 32-bit host systems.

> What's the output of python2 -c 'import sys; print(sys.prefix)'

/usr

![xu-1204-check-issue-89](https://cloud.githubusercontent.com/assets/1223304/6758477/5f7df2ea-cf30-11e4-973b-8171d9a21bfc.png)

![xu-1404-check-issue-89](https://cloud.githubusercontent.com/assets/1223304/6758478/62c18d72-cf30-11e4-8950-1aa36eb49ebd.png)

Additionally, other than running Customizer from Terminal, I prefer to use application launcher called Kupfer. I am using this launcher on both 12.04 and 14.04 32-bit host systems.

![xu-1404-kupfer](https://cloud.githubusercontent.com/assets/1223304/6758491/7b3ad91c-cf30-11e4-92d1-16e0535da950.png)

The launcher detects "Customizer" within the list of applications normally. Although, I did add extra path to `/usr/bin` in Kupfer to find some internal applications such as XFCE setting manager, etc. which are not found by default.

![xu-1204-kupfer-pref](https://cloud.githubusercontent.com/assets/1223304/6758513/a6895b70-cf30-11e4-81d3-5f3e1e3f83f4.png)

If someone can explain how to reproduce this issue, I could try and reconfirm on my test machine.

P.S.: Updated with screenshots.

**Comment by fluxer** [comment]
I asked @GlassSources for the info not you but thanks anyway.

The thing is that since extra files (such as the UI script) reside in <prefix>/share/customizer which by default is taken from whatever PYTHON (by default python2) is set during installation (that would be `make install`) and if one choosed to do the following:

```
make PYTHON=python2.7
sudo make install
```

then run with system default python2 (that's what the shebang is set to) which has prefix different from python2.7 it will cause Customizer to attempt to inject the wrong path where the extra files are to the Python path. That can be a common problem with distros tempering with python/python2 symlinks, for an example on Gentoo changing the default Python interpreted can cause the issue @GlassSources  is facing, I'm well aware of the consequences when I choose such method of "injection". That's why the project used Nuitka in the first place but it had to be dropped.

Even if the shebang is set to what PYTHON is (again, default to python2) this link or file is something an administractor can temper with and will probably have to be resolved for a bit more robust results so that if /usr/bin/python2 points to /usr/bin/python2.7 the shebangs of the scripts are set to /usr/bin/python2.7 (for example look at https://github.com/clearkimura/Customizer/blob/master/data/customizer.desktop.in#L4 where ELEVATOR and PREFIX are set) but that isn't perfect solution either.

In any case, without input from @GlassSources I can not help him overcome this issue and even if I do there is more to be done on this matter, [Cython](http://cython.org/) would be an option but some trickery has to be done to make bundles.

Happy hacking to the future developer :D. Cheers!
