### ISSUE TITLE
EFI Boot from Remastered ISO

### ISSUE THREAD

**Issue by ranseyer** [kamilion/customizer#99]
My System Ubuntu 14.04.2 as Host an an brandnew 14.04.2 ISO without changes. Only remastered. Customizer is from last Week: https://github.com/clearkimura/Customizer/commit/f3bdc01f5a2ca80f19115e11dbe59925498ea300.

Did someone succesfully booted an remastered ISO by an mainboard that supports EFI only ?

When i try to user isohybrid, it tells me that the content of the ISO is wrong:

> root@isobuilder-virtual-machine:/home/customizer# isohybrid -u 006.iso
> isohybrid: 006.iso: unable to find efi image  
> root@isobuilder-virtual-machine:/home/customizer# 

Is here a Problem ? (Case sensitive filenames?)

> root@isobuilder-virtual-machine:/1/EFI# tree
> └── BOOT
>    ├── BOOTx64.EFI
>    └── grubx64.efi

(and: @second Windows thinks the Sticks are defect and want to format them)

PS: Booting with active "EFI" in Virtualbox works with this ISOs. This is no criteria...

**Comment by ranseyer** [comment]
Now im testing this in rebuild.py 

```
misc.system_command(('xorriso', '-as', 'mkisofs', '-r', '-V', \
    distrib + '-' + arch + '-' + release, '-b', 'isolinux/isolinux.bin', \
    '-c', 'isolinux/boot.cat', '-J', '-l', '-no-emul-boot', \
    '-boot-load-size', '4', '-boot-info-table', '-o', iso_file, \
    '-iso-level', '4', '-eltorito-alt-boot', '-e', 'boot/grub/efi.img',\
    '-input-charset', 'utf-8', '.'))
```

> second-last line is new...

**Comment by ghost** [comment]
@ranseyer 

> Did someone succesfully booted an remastered ISO by an mainboard that supports EFI only ?

Negative, because I didn't try and haven't heard anyone did.

Remastering "EFI-capable Ubuntu-based image" is even more niche than "normal Ubuntu-based image" alone. It is not impossible to find: Quick googling leads me to [this answer at askubuntu.com](http://askubuntu.com/questions/457528/how-do-i-create-an-efi-bootable-iso-of-a-customized-version-of-ubuntu).

The link discusses something like "creating dual boot catalog ISO which will boot both EFI and MBR" and shares instructions modified from other source, because it had "point to the wrong locations for the file efi.img." In other words, it is not without issues.

And be careful with EFI. You may have read some news since 2013, whereby some EFI-enabled hardware can be bricked just by [booting Linux distribution](http://linux.slashdot.org/story/13/01/30/1426255/linux-booting-via-uefi-can-brick-samsung-notebooks) or even [booting Windows](http://www.pcworld.com/article/2027819/not-just-linux-windows-can-brick-samsung-laptops-too.html).

I never used `isohybrid` to create bootable USB image before, so I can't suggest for that either. But I found [this post at superuser.com](http://superuser.com/questions/591234/creating-a-bootable-usb-from-command-line-on-linux) explaining how to create that.

Above all, seeing quite number of issues with EFI, I will stick with traditional BIOS 32-bit machine for now. Anyway, we all [might be using 64-bit eventually](http://www.phoronix.com/scan.php?page=news_item&px=MTgxOTQ), but [not any soon](http://news.softpedia.com/news/Ubuntu-32-Bit-Images-Are-Not-Going-Away-Too-Soon-465055.shtml).

**Comment by ranseyer** [comment]
We ship all ISOs as Hybrid ISOs in the last years, We did it with "isohybrid name-of.iso". Then you can prepare your Stick with "dd if=name-of.iso of=/dev/sdx". (Or Win32Disk Imager who does the same as "dd")
With EFI enabled in Virtualbox i can boot this ISOs too. But not with some real hardware.
And: its not possible to run "isohybrid -u name-of.iso" because you will get an error:
"isohybrid: name-of.iso: unable to find efi image"

Examples for our old an since years good tested hybrid-ISOs: http://ftp.gwdg.de/pub/linux/easyvdr/2.0/

Now i had 1st succes with UEFI. But not with the code i have written above. I build now the ISO and enter this command in the ISO folder:

> sudo xorriso -as mkisofs -no-emul-boot -boot-load-size 4 -boot-info-table -iso-level 4 -b isolinux/isolinux.bin -c isolinux/boot.cat -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot -o ../name-of.iso .

Maybe the order of the commands is important too. (cant believe)
With this ISO i can run "isohybrid -u" sucessfully. (isohybrid is hopefully not nessesary, but its a first test because i own  no efi-only hardware...

Thanks for this much links. I will check them for new informations.

ed: Very important: There are machines on the market, they dont have an legacy BIOS anymore. So the can only boot via EFI...

ed2: a check with "dumpet"

```
dumpet -i nameof-UEFI.iso 
Validation Entry:
        Header Indicator: 0x01 (Validation Entry)
        PlatformId: 0x00 (80x86)
        ID: ""
        Checksum: 0x55aa
        Key bytes: 0x55aa
Boot Catalog Default Entry:
        Entry is bootable
        Boot Media emulation type: no emulation
        Media load segment: 0x0 (0000:7c00)
        System type: 0 (0x00)
        Load Sectors: 4 (0x0004)
        Load LBA: 1321 (0x00000529)
Section Header Entry:
        Header Indicator: 0x91 (Final Section Header Entry)
        PlatformId: 0xef (EFI)
        Section Entries: 1
        ID: ""
Boot Catalog Section Entry:
        Entry is bootable
        Boot Media emulation type: no emulation
        Media load address: 0 (0x0000)
        System type: 0 (0x00)
        Load Sectors: 4672 (0x1240)
```

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
